### ISSUE TITLE
Does not work on macOS 13.x?

### ISSUE THREAD

**Issue by LarsEckart** [HanSolo/JDK-Updater#4]
hey,

I'm on 13.6.6 (M1) and just downloaded the latest release and when unpacking the file, I already noticed an overlay over the app icon, that probably doesnt belong to it. and when i then wanted to start the app, I got an error dialog saying `You can’t use this version of the application “JDKUpdater.app” with this version of macOS.`

I'm just wondering if this is a deliberate decision/necessity or maybe just an oversight?

![Screenshot 2024-04-01 at 14 34 32](https://github.com/HanSolo/JDK-Updater/assets/4414802/c4518b69-c9b2-45b9-a74a-20d73cb18a37)

**Comment by HanSolo** [comment]
Yep that's correct, it works from MacOS 14 onwards, which is the reason for the overlay
